### ISSUE TITLE
It doesn't work for github pages

### ISSUE THREAD

**Issue by rusyasoft** [agryaznov/jekyll-telegram-instant-view#1]
Hi this rule doesn't work for pages that are hosted on github pages?

is there anything we can do about it ?
example: https://rusyasoft.github.io/database/2020/04/10/sql-alchemy-migrations-alembic/

**Comment by agryaznov** [comment]
Hi Rustam. I think this one has nothing to do with the hosting method of your blog (be it github pages or any other). The issue is more about your jekyll theme. As far as I see, the theme your blog uses is not [jekyll minima theme](https://github.com/jekyll/minima). Meanwhile the template provided in this repo is designed for that particular theme only.

**Comment by rusyasoft** [comment]
@agryaznov thank You for your reply.

I would like to ask you one more thing. As I see you are really good at making Telegram Instant Views. Can you share some good resources about creating Telegram Instant Views. Because official site doesn't provide enough examples, and I couldn't find much information about it.

Thank You beforehand

**Comment by agryaznov** [comment]
Well, the only documentation I used is from the official site (link is provided in README: https://instantview.telegram.org/docs). Honestly, I find it quite sufficient.
